/**
 * deploy-vulnerable.ts
 *
 * Deploys the vulnerable vault and registers the deployer as owner.
 * Writes the contract address to deployment.json for attack.ts to consume.
 *
 * Prerequisites:
 *   1. docker compose up -d              (start proof server + node + indexer)
 *   2. compact compile contracts/vulnerable.compact contracts/managed/vulnerable
 *
 * Run:
 *   npx ts-node src/deploy-vulnerable.ts
 */

import * as fs   from 'node:fs';
import * as path from 'node:path';

import { NodeZkConfigProvider }      from '@midnight-ntwrk/midnight-js-node-zk-config-provider';
import { indexerPublicDataProvider } from '@midnight-ntwrk/midnight-js-indexer-api';

// The compiled contract module is generated by:
//   compact compile contracts/vulnerable.compact contracts/managed/vulnerable
import * as Vulnerable from '../contracts/managed/vulnerable/index.cjs';

import { CONFIG } from './config.js';
import { vulnerableWitnesses, createVulnerablePrivateState } from './witnesses.js';

async function main(): Promise<void> {
  console.log('=== Deploying vulnerable vault ===');
  console.log(`Proof server : ${CONFIG.proofServerUri}`);
  console.log(`Indexer      : ${CONFIG.indexerUri}`);

  // ZK circuit configuration — loads compiled artifacts and routes prove requests
  const zkConfig = await NodeZkConfigProvider.create(CONFIG.proofServerUri);

  // Public state provider — reads ledger state from the indexer
  const publicDataProvider = indexerPublicDataProvider(
    CONFIG.indexerUri,
    CONFIG.indexerWsUri,
  );

  const providers = { zkConfig, publicDataProvider };

  // Deploy the vulnerable vault.
  // vulnerable.compact declares no witness functions — it relies on the built-in
  // ownPublicKey(), which the wallet automatically provides from the signer's key.
  const contract  = new Vulnerable.Contract(vulnerableWitnesses);
  const deployed  = await contract.deploy(providers, createVulnerablePrivateState());

  console.log(`\nDeployed at: ${deployed.contractAddress}`);

  // Owner calls deposit() to register ownership.
  // This executes:  vault_owner = disclose(ownPublicKey())
  // vault_owner is now PUBLIC LEDGER STATE — visible to any chain observer.
  const tx = await deployed.callTx.deposit();
  await tx.watch();

  const rawState  = await publicDataProvider.queryContractState(deployed.contractAddress);
  const state     = Vulnerable.ledger(rawState);
  const ownerHex  = Buffer.from(state.vault_owner as Uint8Array).toString('hex');

  console.log('\n[!] vault_owner is now public ledger state:');
  console.log(`    ${ownerHex}`);
  console.log('    Any attacker can read this — and ownPublicKey() is unconstrained.');
  console.log('    Run: npx ts-node src/attack.ts\n');

  fs.writeFileSync(
    path.join(process.cwd(), 'deployment.json'),
    JSON.stringify({ contractAddress: deployed.contractAddress, ownerHex }, null, 2),
    'utf8',
  );
}

main().catch((err) => { console.error(err); process.exit(1); });
